import os
import re
import requests
from neo4j import GraphDatabase
from sentence_transformers import SentenceTransformer, CrossEncoder
import numpy as np
from typing import List, Dict, Any, Literal, Tuple
from app.graph_rag.query_classifier import QueryComplexityClassifier


# Statute aliases that may appear in user queries, mapped to a lowercased
# substring expected to be present in the corresponding Document.title node
# in Neo4j. Order matters - longer/more-specific aliases are matched first
# so e.g. "pakistan penal code" wins over "code".
_STATUTE_ALIAS_PATTERNS: List[Tuple[str, str]] = [
    (r'prevention of electronic crimes', 'electronic crimes'),
    (r'pakistan penal code', 'penal code'),
    (r'electronic transactions', 'electronic transactions'),
    (r'pakistan telecommunication\w*', 'telecommunication'),
    (r'telecommunication\w*', 'telecommunication'),
    (r'\bpeca\b', 'electronic crimes'),
    (r'\bppc\b', 'penal code'),
    (r'penal code', 'penal code'),
    (r'\beto\b', 'electronic transactions'),
    (r'\btelecom\b', 'telecommunication'),
    (r'\bconstitution\b', 'constitution'),
]


class LegalGraphRAG:
    EMPTY_GENERATION_PLACEHOLDER = (
        "No response generated by configured model backend."
    )  # Shown when Ollama returns HTTP 200 but an empty "response" string.

    @staticmethod
    def _strip_markdown_json_fence(raw: str) -> str:
        s = (raw or "").strip()
        if not s.startswith("```"):
            return s
        lines = s.split("\n")
        if lines and lines[0].strip().startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        return "\n".join(lines).strip()

    @staticmethod
    def _normalize_env_text(value: str | None) -> str:
        if value is None:
            return ""
        return "".join(ch for ch in value if ch.isprintable() and ord(ch) < 128).strip()

    @staticmethod
    def _normalize_ollama_base_url(url: str) -> str:
        """
        OLLAMA_URL must be the origin only (e.g. https://x.ngrok-free.app).
        If someone pastes a full path used for testing (/api/tags), strip it so
        /api/generate does not become /api/tags/api/generate.
        """
        u = url.rstrip("/")
        lowered = u.lower()
        for suffix in ("/api/tags", "/api/generate"):
            if lowered.endswith(suffix):
                u = u[: -len(suffix)].rstrip("/")
                lowered = u.lower()
        return u

    def __init__(self, 
                neo4j_uri: str,
                neo4j_user: str,
                neo4j_password: str,
                ollama_url: str,
                ollama_model : str = "Llama3.1:8b"):
        self.driver = GraphDatabase.driver(neo4j_uri, auth=(neo4j_user, neo4j_password))
        self.embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
        self.ollama_url = self._normalize_ollama_base_url(
            self._normalize_env_text(ollama_url)
        )
        self.model_name = self._normalize_env_text(ollama_model) or "Llama3.1:8b"
        # Remote GPU (e.g. Kaggle + ngrok): first /api/generate can exceed 120s while the model loads.
        self.ollama_request_timeout = int(os.getenv("OLLAMA_REQUEST_TIMEOUT", "300"))

        # Load query complexity classifier
        self.query_classifier = QueryComplexityClassifier()
        
        # Load re-ranker model for multi-stage retrieval
        try:
            self.reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
            self.use_reranker = True
        except Exception as e:
            print(f"Warning: Could not load re-ranker model: {e}")
            self.use_reranker = False
        
    def close(self):
        self.driver.close()

    def _ollama_http_headers(self) -> dict:
        """Free ngrok may return an HTML interstitial unless this header is set."""
        if "ngrok" in self.ollama_url.lower():
            return {"ngrok-skip-browser-warning": "true"}
        return {}

    def check_ollama_health(self) -> bool:
        """Check if Ollama service (or Ollama-compatible shim) is reachable."""
        try:
            response = requests.get(
                f"{self.ollama_url}/api/tags",
                timeout=5,
                headers=self._ollama_http_headers(),
            )
            return response.status_code == 200
        except Exception:
            return False

    def check_generation_health(self):
        ollama_ok = self.check_ollama_health()
        return {
            "backend": "ollama",
            "healthy": ollama_ok,
            "error": None if ollama_ok else "Ollama-compatible endpoint not reachable",
            "model": self.model_name,
        }

    def _generate_text(self, prompt: str, temperature: float = 0.3, num_predict: int = 800, top_p: float = 0.9) -> str:
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": temperature,
                "num_predict": num_predict,
                "top_p": top_p,
            }
        }

        response = requests.post(
            f"{self.ollama_url}/api/generate",
            json=payload,
            timeout=self.ollama_request_timeout,
            headers=self._ollama_http_headers(),
        )
        response.raise_for_status()
        data = response.json()
        if data.get("error"):
            raise RuntimeError(f"Ollama returned an error: {data['error']}")
        text = (data.get("response") or "").strip()
        return text or self.EMPTY_GENERATION_PLACEHOLDER
    
    def semantic_search(self, query: str, top_k: int = 10) -> List[Dict]:
        query_embedding = self.embedding_model.encode(query)
        
        with self.driver.session() as session:
            cypher_query = """
            CALL db.index.vector.queryNodes(
              'article_embeddings',
              $top_k,
              $query_embedding
            )
            YIELD node, score
            MATCH (d:Document)-[:CONTAINS]->(node)
            RETURN node.id as id,
                   node.article_number as article_number,
                   node.title as title,
                   node.content as content,
                   node.page_number as page_number,
                   node.chapter as chapter,
                   node.part as part,
                   d.title as document_title,
                   d.source_file as source_file,
                   score
            """
            results = session.run(
            cypher_query, 
            parameters={'query_embedding': query_embedding, 'top_k': top_k})
        
            articles = []
            for record in results:
                articles.append({
                    'id': record['id'],
                    'article_number': record['article_number'],
                    'title': record['title'],
                    'content': record['content'],
                    'page_number': record['page_number'],
                    'chapter': record['chapter'],
                    'part': record['part'],
                    'document_title': record['document_title'],
                    'source_file': record['source_file'],
                    'similarity': float(record['score']) # Score is the similarity
                })
            
            return articles
    
    def keyword_search(self, query: str, top_k: int = 8) -> List[Dict]:
        with self.driver.session() as session:
            cypher_query = """
            CALL db.index.fulltext.queryNodes('article_content', $query)
            YIELD node, score
            MATCH (d:Document)-[:CONTAINS]->(node)
            RETURN node.id as id,
                   node.article_number as article_number,
                   node.title as title,
                   node.content as content,
                   node.page_number as page_number,
                   node.chapter as chapter,
                   node.part as part,
                   d.title as document_title,
                   d.source_file as source_file,
                   score
            LIMIT $top_k
            """
            
            results = session.run(cypher_query, parameters={'query': query, 'top_k': top_k})
            
            return [dict(record) for record in results]
    
    def get_related_articles(self, article_id: str, depth: int = 2) -> List[Dict]:
        with self.driver.session() as session:
            # Enhanced to include CITES relationships
            cypher_query = """
            MATCH path = (a:Article {id: $article_id})-[:SIMILAR_TO|RELATES_TO|CITES|RELATED_THROUGH*1..""" + str(depth) + """]->(related)
            WHERE related:Article
            MATCH (d:Document)-[:CONTAINS]->(related)
            RETURN DISTINCT related.id as id,
                   related.article_number as article_number,
                   related.title as title,
                   related.content as content,
                   related.page_number as page_number,
                   related.chapter as chapter,
                   related.part as part,
                   d.title as document_title,
                   d.source_file as source_file,
                   length(path) as distance
            ORDER BY distance
            LIMIT 15
            """
            
            results = session.run(cypher_query, article_id=article_id)
            return [dict(record) for record in results]
    
    def case_semantic_search(self, query: str, top_k: int = 5) -> List[Dict]:
        """
        Semantic search over court cases using vector embeddings
        """
        query_embedding = self.embedding_model.encode(query)
        
        with self.driver.session() as session:
            cypher_query = """
            CALL db.index.vector.queryNodes(
              'case_embeddings',
              $top_k,
              $query_embedding
            )
            YIELD node, score
            RETURN node.id as id,
                   node.citation as citation,
                   node.title as title,
                   node.summary as summary,
                   node.pdf_data as pdf_data,
                   node.court as court,
                   node.date as date,
                   node.judge as judge,
                   node.pdf_link as pdf_link,
                   node.cyber_law_reason as cyber_law_reason,
                   node.cyber_law_triggers_json as cyber_law_triggers_json,
                   node.winner as winner,
                   score
            """
            
            try:
                results = session.run(cypher_query,
                    query_embedding=query_embedding,
                    top_k=top_k
                )
                
                cases = []
                for record in results:
                    cases.append({
                        'id': record['id'],
                        'citation': record['citation'],
                        'title': record['title'],
                        'summary': record['summary'],
                        'pdf_data': record['pdf_data'],
                        'court': record['court'],
                        'date': record['date'],
                        'judge': record['judge'],
                        'pdf_link': record['pdf_link'],
                        'cyber_law_reason': record['cyber_law_reason'],
                        'cyber_law_triggers_json': record['cyber_law_triggers_json'],
                        'winner': record['winner'],
                        'similarity': float(record['score']),
                        'type': 'case'
                    })
                
                return cases
            except Exception as e:
                print(f"Case search error: {e}")
                return []
    
    def case_keyword_search(self, query: str, top_k: int = 5) -> List[Dict]:
        """
        Keyword search over court case titles and summaries
        """
        with self.driver.session() as session:
            cypher_query = """
            CALL db.index.fulltext.queryNodes('case_title', $query)
            YIELD node, score
            RETURN node.id as id,
                   node.citation as citation,
                   node.title as title,
                   node.summary as summary,
                   node.pdf_data as pdf_data,
                   node.court as court,
                   node.date as date,
                   node.judge as judge,
                   node.pdf_link as pdf_link,
                   node.cyber_law_reason as cyber_law_reason,
                   node.cyber_law_triggers_json as cyber_law_triggers_json,
                   node.winner as winner,
                   score
            LIMIT $top_k
            """
            
            try:
                results = session.run(cypher_query, {'query': query, 'top_k': top_k})
                
                cases = []
                for record in results:
                    cases.append({
                        'id': record['id'],
                        'citation': record['citation'],
                        'title': record['title'],
                        'summary': record['summary'],
                        'pdf_data': record['pdf_data'],
                        'court': record['court'],
                        'date': record['date'],
                        'judge': record['judge'],
                        'pdf_link': record['pdf_link'],
                        'cyber_law_reason': record['cyber_law_reason'],
                        'cyber_law_triggers_json': record['cyber_law_triggers_json'],
                        'winner': record['winner'],
                        'score': float(record['score']),
                        'type': 'case'
                    })
                
                return cases
            except Exception as e:
                print(f"Case keyword search error: {e}")
                return []
    
    def get_cases_citing_article(self, article_id: str, top_k: int = 5) -> List[Dict]:
        """
        Get court cases that cite a specific article
        """
        with self.driver.session() as session:
            cypher_query = """
            MATCH (c:Case)-[:CITES]->(a:Article {id: $article_id})
            RETURN c.id as id,
                   c.citation as citation,
                   c.title as title,
                   c.summary as summary,
                   c.pdf_data as pdf_data,
                   c.court as court,
                   c.date as date,
                   c.judge as judge,
                   c.pdf_link as pdf_link,
                   c.cyber_law_reason as cyber_law_reason,
                   c.cyber_law_triggers_json as cyber_law_triggers_json,
                   c.winner as winner
            ORDER BY c.date DESC
            LIMIT $top_k
            """
            
            results = session.run(cypher_query, article_id=article_id, top_k=top_k)
            
            cases = []
            for record in results:
                cases.append({
                    'id': record['id'],
                    'citation': record['citation'],
                    'title': record['title'],
                    'summary': record['summary'],
                    'pdf_data': record['pdf_data'],
                    'court': record['court'],
                    'date': record['date'],
                    'judge': record['judge'],
                    'pdf_link': record['pdf_link'],
                    'cyber_law_reason': record['cyber_law_reason'],
                    'cyber_law_triggers_json': record['cyber_law_triggers_json'],
                    'winner': record['winner'],
                    'type': 'case'
                })
            
            return cases
    
    def get_all_cases(self, limit: int = 100) -> List[Dict]:
        """
        Get all court cases from the graph
        """
        with self.driver.session() as session:
            cypher_query = """
            MATCH (c:Case)
            RETURN c.id as id,
                   c.citation as citation,
                   c.title as title,
                   c.summary as summary,
                   c.court as court,
                   c.date as date,
                   c.judge as judge,
                   c.pdf_link as pdf_link,
                   c.cyber_law_reason as cyber_law_reason,
                   c.winner as winner
            ORDER BY c.date DESC
            LIMIT $limit
            """
            
            try:
                results = session.run(cypher_query, parameters={'limit': limit})
                
                cases = []
                for record in results:
                    cases.append({
                        'id': record['id'],
                        'citation': record['citation'],
                        'title': record['title'],
                        'summary': record['summary'],
                        'court': record['court'],
                        'date': record['date'],
                        'judge': record['judge'],
                        'pdf_link': record['pdf_link'],
                        'cyber_law_reason': record['cyber_law_reason'],
                        'winner': record['winner'],
                        'type': 'case'
                    })
                
                return cases
            except Exception as e:
                print(f"Error fetching all cases: {e}")
                return []

    
    def _extract_statute_citations(self, query: str) -> List[Tuple[str, str]]:
        """
        Extract explicit (article_number, statute_title_fragment) pairs from a
        natural language query.

        Handles forms like:
          "Section 20 of PECA 2016"
          "Sections 20, 21(1), and 24(1) of PECA 2016-2025"
          "Section 171-G of PPC"
          "Sections 2R(1)(b), (e), (h), 11, and 26A of PECA 2016-2025"
          "...offense under PECA 2016 was committed, as per Sections 29, 30, and 44..."

        Strategy: for each "section[s]" occurrence we look first in a forward
        window (~250 chars) for a statute alias. If none is found there, we
        fall back to the nearest statute alias mentioned anywhere else in the
        query. Returned section numbers are lowercased to match how
        article_number is stored in Neo4j (e.g. "26a", "2r", "171-g"). The
        statute_title_fragment is a lowercase substring expected to appear in
        Document.title (e.g. "electronic crimes" matches both PECA 2016 and
        the 2025 amendment).
        """
        if not query:
            return []

        q_lower = query.lower()

        # Pre-compute every statute alias hit in the query (position, fragment)
        # so we can fall back to the nearest one when a "section[s]" block
        # has no statute in its forward window.
        all_statute_hits: List[Tuple[int, str]] = []
        for pat, frag in _STATUTE_ALIAS_PATTERNS:
            for m in re.finditer(pat, q_lower):
                all_statute_hits.append((m.start(), frag))

        pairs: List[Tuple[str, str]] = []

        for section_match in re.finditer(r'\bsections?\b', q_lower):
            window_start = section_match.end()
            window = q_lower[window_start:window_start + 250]

            statute_fragment: str | None = None
            statute_pos = len(window)
            for pat, frag in _STATUTE_ALIAS_PATTERNS:
                m = re.search(pat, window)
                if m and m.start() < statute_pos:
                    statute_fragment = frag
                    statute_pos = m.start()

            if statute_fragment is None:
                if not all_statute_hits:
                    continue
                section_pos = section_match.start()
                _, statute_fragment = min(
                    all_statute_hits,
                    key=lambda hit: abs(hit[0] - section_pos),
                )
                section_window = window
            else:
                section_window = window[:statute_pos]

            section_window = re.sub(r'\([^)]*\)', '', section_window)

            for sec_match in re.finditer(r'\b(\d+[a-z]?(?:-[a-z]+)?)\b', section_window):
                section_num = sec_match.group(1).strip()
                pairs.append((section_num, statute_fragment))

        seen = set()
        deduped: List[Tuple[str, str]] = []
        for sec, stat in pairs:
            key = (sec, stat)
            if key not in seen:
                seen.add(key)
                deduped.append((sec, stat))
        return deduped

    def _anchor_articles_by_citation(self, citations: List[Tuple[str, str]]) -> List[Dict]:
        """
        Look up exact Article nodes for explicit (section_number, statute_fragment)
        citations and return them shaped like other retrieval candidates with a
        guaranteed-top scoring profile so they survive any downstream filtering.
        """
        if not citations:
            return []

        cypher_query = """
        UNWIND $pairs AS pair
        MATCH (d:Document)-[:CONTAINS]->(a:Article)
        WHERE toLower(a.article_number) = pair.section
          AND toLower(d.title) CONTAINS pair.statute
        RETURN a.id AS id,
               a.article_number AS article_number,
               a.title AS title,
               a.content AS content,
               a.page_number AS page_number,
               a.chapter AS chapter,
               a.part AS part,
               d.title AS document_title,
               d.source_file AS source_file
        """

        params_pairs = [{"section": sec, "statute": stat} for sec, stat in citations]

        try:
            with self.driver.session() as session:
                results = session.run(cypher_query, parameters={"pairs": params_pairs})
                records = list(results)
        except Exception as e:
            print(f"Citation anchor lookup failed: {e}")
            return []

        anchored: List[Dict] = []
        seen_ids: set[str] = set()
        for record in records:
            if record['id'] in seen_ids:
                continue
            seen_ids.add(record['id'])
            anchored.append({
                'id': record['id'],
                'article_number': record['article_number'],
                'title': record['title'],
                'content': record['content'],
                'page_number': record['page_number'],
                'chapter': record['chapter'],
                'part': record['part'],
                'document_title': record['document_title'],
                'source_file': record['source_file'],
                'similarity': 1.0,
                'semantic_score': 1.0,
                'keyword_score': 1.0,
                'graph_score': 0.0,
                'case_score': 0.0,
                'combined_score': 1.0,
                'rerank_score': 1.0,
                'final_score': 1.0,
                'type': 'article',
                'anchored': True,
            })
        return anchored

    def multi_stage_retrieval(self, query: str, top_k: int = 10) -> List[Dict]:
        """
        Multi-stage retrieval: Broad recall → Precise re-ranking
        Stage 1: Cast wide net with multiple retrieval strategies
        Stage 2: Re-rank using cross-encoder for precision
        """
        # Read tunable flags once. Defaults preserve baseline behavior when set to "0".
        anchor_enabled = os.getenv("RETRIEVAL_CITATION_ANCHOR", "1") == "1"
        tuned_weights = os.getenv("RETRIEVAL_TUNED_WEIGHTS", "1") == "1"

        if tuned_weights:
            article_w_semantic, article_w_keyword, article_w_graph = 0.45, 0.35, 0.20
            rerank_blend_combined, rerank_blend_score = 0.5, 0.5
            rerank_threshold = 0.10
        else:
            article_w_semantic, article_w_keyword, article_w_graph = 0.5, 0.3, 0.2
            rerank_blend_combined, rerank_blend_score = 0.3, 0.7
            rerank_threshold = 0.20

        # Stage 1: Broad Recall (get top 30 candidates)
        print("Stage 1: Broad recall...")
        
        # Statutory law retrieval
        semantic_results = self.semantic_search(query, top_k=15)  # Reduced to make room for cases
        keyword_results = self.keyword_search(query, top_k=10)
        
        # Case law retrieval (NEW - Phase 3)
        case_semantic_results = self.case_semantic_search(query, top_k=5)
        case_keyword_results = self.case_keyword_search(query, top_k=3)
        
        print(f"  - Found {len(semantic_results)} statutory articles (semantic)")
        print(f"  - Found {len(keyword_results)} statutory articles (keyword)")
        print(f"  - Found {len(case_semantic_results)} court cases (semantic)")
        print(f"  - Found {len(case_keyword_results)} court cases (keyword)")
        
        # Expand via graph traversal
        graph_results = []
        seen_ids = set()
        
        for result in semantic_results[:5]:  # Top 5 semantic matches
            related = self.get_related_articles(result['id'], depth=2)
            for r in related:
                if r['id'] not in seen_ids:
                    graph_results.append(r)
                    seen_ids.add(r['id'])
        
        # Get cases citing top articles
        case_citations = []
        for result in semantic_results[:3]:  # Top 3 articles
            citing_cases = self.get_cases_citing_article(result['id'], top_k=2)
            case_citations.extend(citing_cases)
        
        # Merge all candidates
        all_candidates = {}
        
        # Add statutory articles
        for result in semantic_results:
            all_candidates[result['id']] = {
                **result,
                'semantic_score': result['similarity'],
                'keyword_score': 0,
                'graph_score': 0,
                'case_score': 0,
                'type': 'article'
            }
        
        for result in keyword_results:
            if result['id'] in all_candidates:
                all_candidates[result['id']]['keyword_score'] = result['score']
            else:
                all_candidates[result['id']] = {
                    **result,
                    'semantic_score': 0,
                    'keyword_score': result['score'],
                    'graph_score': 0,
                    'case_score': 0,
                    'type': 'article'
                }
        
        for result in graph_results[:10]:  # Limit graph expansion
            if result['id'] not in all_candidates:
                all_candidates[result['id']] = {
                    **result,
                    'semantic_score': 0,
                    'keyword_score': 0,
                    'graph_score': 1.0 / (result.get('distance', 1) + 1),
                    'case_score': 0,
                    'type': 'article'
                }
        
        # Add court cases (NEW)
        for result in case_semantic_results:
            all_candidates[result['id']] = {
                **result,
                'semantic_score': result['similarity'],
                'keyword_score': 0,
                'graph_score': 0,
                'case_score': 0.9,  # Boost score for direct case matches
                'type': 'case'
            }
        
        for result in case_keyword_results:
            if result['id'] in all_candidates:
                all_candidates[result['id']]['keyword_score'] = result.get('score', 0)
            else:
                all_candidates[result['id']] = {
                    **result,
                    'semantic_score': 0,
                    'keyword_score': result.get('score', 0),
                    'graph_score': 0,
                    'case_score': 0.8,
                    'type': 'case'
                }
        
        for result in case_citations:
            if result['id'] not in all_candidates:
                all_candidates[result['id']] = {
                    **result,
                    'semantic_score': 0,
                    'keyword_score': 0,
                    'graph_score': 0,
                    'case_score': 0.7,  # Lower boost for indirect case matches
                    'type': 'case'
                }
        
        # Calculate initial combined score
        for result in all_candidates.values():
            if result.get('type') == 'case':
                # Different weighting for cases
                result['combined_score'] = (
                    result['semantic_score'] * 0.4 +
                    result['keyword_score'] * 0.2 + 
                    result['case_score'] * 0.4
                )
            else:
                # Article weighting (tunable via RETRIEVAL_TUNED_WEIGHTS)
                result['combined_score'] = (
                    result['semantic_score'] * article_w_semantic +
                    result['keyword_score'] * article_w_keyword +
                    result['graph_score'] * article_w_graph
                )
        
        # Get top 30 candidates
        candidates = sorted(all_candidates.values(), 
                          key=lambda x: x['combined_score'], 
                          reverse=True)[:30]
        
        # Stage 2: Re-ranking with cross-encoder
        if self.use_reranker and len(candidates) > 0:
            print("Stage 2: Re-ranking with cross-encoder...")
            
            # Build text for re-ranking (handle both articles and cases)
            pairs = []
            for c in candidates:
                if c.get('type') == 'case':
                    # Prefer full PDF text; fall back to summary
                    pdf = c.get('pdf_data') or ''
                    body = pdf[:1500] if (pdf and not pdf.startswith('[ERROR')) else c.get('summary', '')
                    text = f"{c.get('title', '')} {body}"[:1500]
                else:
                    text = c.get('content', '')[:1500]
                pairs.append((query, text))
            
            rerank_scores = self.reranker.predict(pairs)
            
            for candidate, score in zip(candidates, rerank_scores):
                # Apply sigmoid to normalize logit to 0-1
                sigmoid_score = 1 / (1 + np.exp(-float(score)))
                candidate['rerank_score'] = sigmoid_score

                # Combine original score with rerank score (blend tunable via RETRIEVAL_TUNED_WEIGHTS)
                candidate['final_score'] = (
                    candidate['combined_score'] * rerank_blend_combined +
                    candidate['rerank_score'] * rerank_blend_score
                )

            # Filter low relevance (threshold tunable via RETRIEVAL_TUNED_WEIGHTS)
            candidates = [c for c in candidates if c.get('final_score', 0) >= rerank_threshold]

            # Sort by final score
            candidates = sorted(candidates,
                              key=lambda x: x.get('final_score', x['combined_score']),
                              reverse=True)

        # Citation anchor injection: explicitly cited sections (e.g. "Section 20 of PECA 2016")
        # are looked up directly and prepended to the result so they always appear in top_k.
        if anchor_enabled:
            citations = self._extract_statute_citations(query)
            if citations:
                anchored = self._anchor_articles_by_citation(citations)
                if anchored:
                    print(f"  - Anchored {len(anchored)} explicitly-cited article(s)")
                    existing_ids = {c.get('id') for c in candidates}
                    new_anchors = [a for a in anchored if a.get('id') not in existing_ids]
                    candidates = new_anchors + candidates

        return candidates[:top_k]
        
    def rerank(self, query: str, documents: List[Dict], top_k: int = 10, threshold: float = 0.20) -> List[Dict]:
        """
        Re-rank a list of documents using the CrossEncoder model
        """
        if not self.use_reranker or not documents:
            return documents[:top_k]
            
        print(f"   Reranking {len(documents)} documents...")
        
        # Build text for re-ranking
        pairs = []
        for doc in documents:
            if doc.get('type') == 'case':
                pdf = doc.get('pdf_data') or ''
                body = pdf[:1500] if (pdf and not pdf.startswith('[ERROR')) else doc.get('summary', '')
                text = f"{doc.get('title', '')} {body}"[:1500]
            else:
                text = f"{doc.get('title', '')} {doc.get('content', '')}"[:1500]
            pairs.append((query, text))
            
        rerank_scores = self.reranker.predict(pairs)
        
        filtered_docs = []
        for doc, score in zip(documents, rerank_scores):
            # Apply sigmoid to normalize logit to 0-1
            sigmoid_score = 1 / (1 + np.exp(-float(score)))
            doc['rerank_score'] = sigmoid_score
            
            # Combine original score with rerank score (weighted)
            current_score = doc.get('combined_score', doc.get('similarity', 0))
            doc['final_score'] = (current_score * 0.3 + doc['rerank_score'] * 0.7)
            
            # Filter low relevance
            if doc['final_score'] >= threshold:
                filtered_docs.append(doc)
            
        # Sort by final score
        filtered_docs.sort(key=lambda x: x.get('final_score', 0), reverse=True)
        
        return filtered_docs[:top_k]
    
    def hyde_retrieval(self, query: str, top_k: int = 10) -> List[Dict]:
        """
        HyDE (Hypothetical Document Embeddings) retrieval
        Generate a hypothetical legal answer, embed it, then find similar articles
        """
        print("HyDE: Generating hypothetical answer...")
        
        # Step 1: Generate hypothetical answer
        hyde_prompt = f"""Generate a hypothetical legal answer from Pakistani law statutes for this question.
Write it in the formal style of legal statutes (like sections from CrPC, PPC, Constitution).
DO NOT make up section numbers. Just write the legal content.

Question: {query}

Hypothetical Legal Text:"""
        
        try:
            hypothetical_answer = self._generate_text(
                prompt=hyde_prompt,
                temperature=0.5,
                num_predict=300,
                top_p=0.9
            )
            
            if not hypothetical_answer:
                print("HyDE: No hypothetical answer generated, falling back to direct search")
                return self.semantic_search(query, top_k=top_k)
            
            print(f"HyDE: Generated hypothetical text ({len(hypothetical_answer)} chars)")
            
            # Step 2: Embed hypothetical answer
            hypo_embedding = self.embedding_model.encode(hypothetical_answer)
            
            # Step 3: Find similar articles using hypothetical embedding
            with self.driver.session() as session:
                cypher_query = """
                CALL db.index.vector.queryNodes(
                  'article_embeddings',
                  $top_k,
                  $query_embedding
                )
                YIELD node, score
                MATCH (d:Document)-[:CONTAINS]->(node)
                RETURN node.id as id,
                       node.article_number as article_number,
                       node.title as title,
                       node.content as content,
                       node.page_number as page_number,
                       node.chapter as chapter,
                       node.part as part,
                       d.title as document_title,
                       d.source_file as source_file,
                       score
                """
                results = session.run(
                    cypher_query, 
                    query_embedding=hypo_embedding.tolist(), 
                    top_k=top_k
                )
            
                articles = []
                for record in results:
                    articles.append({
                        'id': record['id'],
                        'article_number': record['article_number'],
                        'title': record['title'],
                        'content': record['content'],
                        'page_number': record['page_number'],
                        'chapter': record['chapter'],
                        'part': record['part'],
                        'document_title': record['document_title'],
                        'source_file': record['source_file'],
                        'similarity': float(record['score']),
                        'hyde_score': float(record['score'])
                    })
                
                return articles
                
        except Exception as e:
            print(f"HyDE retrieval failed: {e}")
            return self.semantic_search(query, top_k=top_k)
    
    def extract_relevant_clauses(self, article: Dict, query: str, max_clauses: int = 3) -> List[str]:
        """
        Extract most relevant clauses from an article instead of using entire content
        Returns clause-level precision for better context
        """
        with self.driver.session() as session:
            # Get all clauses for this article
            clause_query = """
            MATCH (a:Article {id: $article_id})-[:CONTAINS]->(c:Clause)
            OPTIONAL MATCH (c)-[:CONTAINS]->(sc:SubClause)
            RETURN c.id as clause_id, 
                   c.clause_number as clause_number,
                   c.text as clause_text,
                   collect(sc.text) as sub_clause_texts
            """
            
            results = session.run(clause_query, article_id=article['id'])
            clauses = list(results)
            
            if not clauses:
                # No clauses found, return article content if available
                if 'content' in article and article['content']:
                    return [article['content']]
                else:
                    return []  # No content available
            
            # Score each clause based on similarity to query
            query_emb = self.embedding_model.encode(query)
            clause_scores = []
            
            for clause in clauses:
                # Combine clause text with sub-clauses
                full_text = clause['clause_text']
                if clause['sub_clause_texts']:
                    full_text += " " + " ".join(clause['sub_clause_texts'])
                
                clause_emb = self.embedding_model.encode(full_text)
                similarity = np.dot(query_emb, clause_emb) / (
                    np.linalg.norm(query_emb) * np.linalg.norm(clause_emb)
                )
                
                clause_scores.append({
                    'clause_number': clause['clause_number'],
                    'text': full_text,
                    'similarity': float(similarity)
                })
            
            # Sort by similarity and return top N clauses
            clause_scores.sort(key=lambda x: x['similarity'], reverse=True)
            return [c['text'] for c in clause_scores[:max_clauses]]
    
    def hybrid_search(self, query: str, top_k: int = 10) -> List[Dict]:
        semantic_results = self.semantic_search(query, top_k=10)

        print("Semantic Results:")
        for res in semantic_results:
            print(f"{res['document_title']} - Article {res['article_number']} (Score: {res['similarity']})")
        
        keyword_results = self.keyword_search(query, top_k=8)

        related_articles = []

        for kw_result in keyword_results:
            related = self.get_related_articles(kw_result['id'], depth=2)
            related_articles.extend(related)

        for sm_result in semantic_results:
            related = self.get_related_articles(sm_result['id'], depth=2)
            related_articles.extend(related)
        
        all_results = {}
        
        for result in semantic_results:
            all_results[result['id']] = {
                **result,
                'semantic_score': result['similarity'],
                'keyword_score': 0,
                'related_score': 0
            }
        
        for result in keyword_results:
            if result['id'] in all_results:
                all_results[result['id']]['keyword_score'] = result['score']
            else:
                all_results[result['id']] = {
                    **result,
                    'semantic_score': 0,
                    'keyword_score': result['score'],
                    'related_score': 0
                }

        for result in related_articles:
            if result['id'] in all_results:
                continue
            all_results[result['id']] = {
                **result,
                'semantic_score': 0,
                'keyword_score': 0,
                'related_score': 1 / result['distance']
            }
        
        for result in all_results.values():
            result['combined_score'] = (
                result['semantic_score'] * 0.15 +
                result['keyword_score'] * 0.15 + 
                result['related_score'] * 0.70)
        
        sorted_results = sorted(all_results.values(), 
                               key=lambda x: x['combined_score'], 
                               reverse=True)
        
        return sorted_results[:top_k]


    def build_context(self, items: List[Dict], query: str = "", max_words: int = 2000,
                     use_clause_level: bool = True) -> str:
        """
        Build hierarchical context with clause-level precision
        Supports both statutory articles and court cases
        
        Args:
            items: List of retrieved articles and/or cases
            query: Original query for clause-level filtering
            max_words: Maximum context size in words
            use_clause_level: If True, extracts relevant clauses instead of full articles
        """
        seen_ids = set()
        context_chunks = []
        total_words = 0
        
        # Separate articles and cases
        articles = [item for item in items if item.get('type') != 'case']
        cases = [item for item in items if item.get('type') == 'case']

        # Process statutory articles first
        for i, article in enumerate(articles, 1):
            if article["id"] in seen_ids:
                continue
            seen_ids.add(article["id"])
            
            # Build article header
            header = (
                f"[Statutory Law {i}]\n"
                f"Document: {article.get('document_title', 'N/A')}\n"
                f"Article {article.get('article_number', 'N/A')}: {article.get('title', 'N/A')}\n"
            )
            
            # Get content: either relevant clauses or full content
            if use_clause_level and query and article.get('content'):
                relevant_clauses = self.extract_relevant_clauses(article, query, max_clauses=3)
                if relevant_clauses:
                    content = "Relevant Clauses:\n" + "\n".join(f"- {clause}" for clause in relevant_clauses)
                else:
                    content = f"Content: {article.get('content', 'N/A')}"
            else:
                content = f"Content: {article.get('content', 'N/A')}"
            
            text = header + content + "\n\n"

            words = len(text.split())
            if total_words + words > max_words:
                if total_words + len(header.split()) < max_words:
                    remaining_words = max_words - total_words - len(header.split())
                    content_words = content.split()[:remaining_words]
                    truncated_text = header + " ".join(content_words) + "...\n\n"
                    context_chunks.append(truncated_text)
                break

            context_chunks.append(text)
            total_words += words
        
        # Process court cases
        for i, case in enumerate(cases, 1):
            if case["id"] in seen_ids:
                continue
            seen_ids.add(case["id"])
            
            header = (
                f"[Case Law {i}]\n"
                f"Citation: {case.get('citation', 'N/A')}\n"
                f"Court: {case.get('court', 'N/A')}\n"
                f"Date: {case.get('date', 'N/A')}\n"
                f"Title: {case.get('title', 'N/A')}\n"
            )
            
            # Use full PDF text when available; fall back to summary
            pdf = case.get('pdf_data') or ''
            has_pdf = bool(pdf) and not pdf.startswith('[ERROR')
            if has_pdf:
                # First 1500 chars of the judgment covers the key reasoning
                content = f"Judgment Text:\n{pdf[:1500]}\n"
            else:
                content = f"Summary: {case.get('summary', 'N/A')}\n"
            
            if case.get('pdf_link'):
                content += f"Full Judgment: {case['pdf_link']}\n"
            
            text = header + content + "\n\n"
            
            words = len(text.split())
            if total_words + words > max_words:
                if total_words + len(header.split()) < max_words:
                    remaining_words = max_words - total_words - len(header.split())
                    content_words = content.split()[:remaining_words]
                    truncated_text = header + " ".join(content_words) + "...\n\n"
                    context_chunks.append(truncated_text)
                break
            
            context_chunks.append(text)
            total_words += words

        return "".join(context_chunks)

    
    def generate_answer_ollama(
        self,
        query: str,
        context: str,
        *,
        response_format: Literal["json", "text"] = "json",
    ) -> str:
        if response_format == "text":
            system_prompt = """You are a legal drafting assistant for Pakistani law.
Output clear, well-structured Markdown only (no JSON). Use headings and bullet lists as appropriate.
Be formal and court-ready where the user asks for a draft."""
            user_prompt = f"""Task / question:
{query}

Background and references:
{context}

Write the document or answer in Markdown."""
        else:
            system_prompt = """You are an AI Legal Advisor specializing in Pakistani law.

OUTPUT RULES (mandatory):
1. Your entire reply must be parseable as JSON: the first character must be `{` and the last must be `}`.
2. Do not write reminders, titles, or phrases like "Do not add text" outside the JSON. Do not wrap the JSON in markdown code fences (no ```).
3. Use double quotes for all JSON keys and string values. Escape internal double quotes in strings as \\".
4. String values are plain text only (no nested markdown fences).

CRITICAL LEGAL RULES:
1. Use ONLY statutes/cases from the context that DIRECTLY answer the question; ignore irrelevant context.
2. Be concise; simple language for lay readers.
3. At most 4 entries in legalBasis; prefer 2 highly relevant citations over many weak ones.

JSON SCHEMA (exact keys):
{
  "directAnswer": "<2-4 sentences answering the question>",
  "legalBasis": [
    { "citation": "<e.g. Article 497 of Criminal Procedure Code 1898>", "explanation": "<brief plain-language note>" }
  ],
  "whatThisMeans": "<what this implies for the user's situation>",
  "nextSteps": ["<optional practical step>", "..."],
  "disclaimer": "<e.g. general information only; consult a qualified lawyer for case-specific advice>"
}

If nextSteps does not apply, use an empty array []. The disclaimer field is required."""

            user_prompt = (
                f"""User question:
{query}

Legal context (statutes and cases):
{context}

"""
                + "Reply with nothing except the JSON object (first character `{`, last character `}`)."
            )

        try:
            answer = self._generate_text(
                prompt=f"{system_prompt}\n\n{user_prompt}",
                temperature=0.3,
                num_predict=1600 if response_format == "json" else 1200,
                top_p=0.9,
            )
            if not answer:
                answer = self.EMPTY_GENERATION_PLACEHOLDER
            if answer != self.EMPTY_GENERATION_PLACEHOLDER:
                if response_format == "json":
                    answer = self._strip_markdown_json_fence(answer)
                elif (
                    response_format == "text"
                    and answer
                    and "consult" not in answer.lower()
                    and "lawyer" not in answer.lower()
                ):
                    answer += "\n\n---\nNote: This information is for general understanding only. For specific legal matters affecting your case, please consult a qualified lawyer."

            return answer

        except (requests.exceptions.RequestException, RuntimeError) as e:
            return f"Error communicating with Ollama: {str(e)}"
    

    def _decompose_query(self, query: str) -> List[str]:
        """
        Transforms generic queries into legal queries with Pakistani legal terminology.
        Returns legal-focused sub-questions optimized for retrieval.
        """

        system_prompt = """You are a Pakistani legal expert assistant. Your task is to transform user questions into legal terminology queries.

Instructions:
1. Convert generic questions into legal terminology used in Pakistani legislation
2. Break complex questions into focused legal sub-queries
3. Use specific legal terms (e.g., "property transfer" → "title deed registration", "accident" → "tort liability")
4. Reference Pakistani legal concepts (FIR, bail, jurisdiction, cause of action, etc.)
5. Return ONLY the legal queries, one per line, starting with "-"
6. Keep queries concise and focused on retrieving relevant legal articles

Examples:
Generic: "What if someone hits my car?"
Legal Queries:
- Motor vehicle accident liability under tort law
- Compensation claims for vehicle damage
- Criminal negligence in road accidents

Generic: "Can I get my money back from a bad deal?"
Legal Queries:
- Contract breach remedies in Pakistani law
- Rescission and restitution of agreements
- Fraud in contractual agreements

Generic: "My landlord won't fix the house"
Legal Queries:
- Landlord obligations for property maintenance
- Tenant rights for habitable premises
- Remedies for breach of tenancy agreement

Now convert the user's question:"""

        user_prompt = f"User Question: {query}\n\nLegal Queries:"

        try:
            text = self._generate_text(
                prompt=f"{system_prompt}\n\n{user_prompt}",
                temperature=0.2,
                num_predict=300,
                top_p=0.9
            )
            if not text:
                return [query]

            lines = [line.strip() for line in text.split("\n") if line.strip()]
            sub_questions = []

            for line in lines:
                # Handle -, *, •
                if line.startswith(("-", "*", "•")):
                    cleaned = line[1:].strip()
                    if cleaned and len(cleaned) > 10:  # Filter out too short queries
                        sub_questions.append(cleaned)

                # Handle numbered lists: "1. xxx" or "1) xxx"
                elif line[0].isdigit():
                    cleaned = line.split(".", 1)[-1].split(")", 1)[-1].strip()
                    if cleaned and len(cleaned) > 10:
                        sub_questions.append(cleaned)

            # Return legal queries if found, otherwise enhance the original query
            if sub_questions:
                return sub_questions[:4]  # Limit to 4 most relevant queries
            else:
                # Fallback: Return original query
                return [query]

        except Exception as e:
            print(f"Query decomposition failed: {e}")
            return [query]


    def query(self, user_question: str, use_multi_stage: bool = None) -> Dict[str, Any]:
        """
        Main query method with adaptive retrieval based on query complexity
        
        Args:
            user_question: The user's legal question
            use_multi_stage: If None (default), automatically determined by complexity.
                           If True/False, overrides automatic determination.
        """
        print(f"Processing query: {user_question}")
        
        # Classify query complexity for adaptive retrieval
        strategy = self.query_classifier.get_retrieval_strategy(user_question)
        complexity = strategy['complexity']
        
        print(f"Query complexity: {complexity.upper()}")
        print(f"Strategy: {strategy['description']}")
        
        # Override strategy if explicitly specified
        if use_multi_stage is not None:
            strategy['use_multi_stage'] = use_multi_stage
            print(f"  (Multi-stage override: {use_multi_stage})")

        print("Decomposing query...")
        sub_questions = self._decompose_query(user_question)
        print(f"Sub-questions: {sub_questions}")

        collected = {}

        for sq in sub_questions:
            print(f"Searching for: {sq}")
            
            # Use strategy-determined retrieval method
            if strategy['use_multi_stage'] and self.use_reranker:
                results = self.multi_stage_retrieval(sq, top_k=strategy['top_k'])
            else:
                results = self.hybrid_search(sq, top_k=strategy['top_k'])

            for article in results:
                # Keep the best score if duplicate
                if article["id"] in collected:
                    existing_score = collected[article["id"]].get("combined_score", 0)
                    new_score = article.get("final_score", article.get("combined_score", 0))
                    if new_score > existing_score:
                        collected[article["id"]] = article
                else:
                    collected[article["id"]] = article

        articles = list(collected.values())

        if not articles:
            return {
                "answer": "No relevant legal articles were found for your question.",
                "sources": [],
                "context": "",
                "sub_questions": sub_questions,
                "complexity": complexity
            }

        # Sort by final_score if available, otherwise combined_score
        articles.sort(key=lambda x: x.get("final_score", x.get("combined_score", 0)), reverse=True)

        # Filter articles with relevance threshold BEFORE building context
        # This prevents irrelevant articles from being sent to LLM
        RELEVANCE_THRESHOLD = -1.0  # Filter out very low-relevance articles
        relevant_articles = [
            a for a in articles 
            if a.get("final_score", a.get("combined_score", 0)) >= RELEVANCE_THRESHOLD
        ]
        
        # If filtering removed everything, keep top 5 anyway
        if not relevant_articles:
            relevant_articles = articles[:5]
        
        print(f"  Filtered to {len(relevant_articles)} relevant articles (threshold: {RELEVANCE_THRESHOLD})")

        # Use strategy-determined context size
        top_articles = relevant_articles[:12]
        context = self.build_context(
            top_articles, 
            query=user_question, 
            max_words=strategy['max_words'],
            use_clause_level=True
        )

        print("Generating final answer...")
        answer = self.generate_answer_ollama(user_question, context)

        sources = []
        for a in top_articles:
            if a.get("type") == "case":
                sources.append({
                    "document": a.get("court", "Case Law"),
                    "article": a.get("citation", "N/A"),
                    "title": a.get("title", ""),
                    "page_number": None,
                    "source_file": "",
                    "pdf_link": a.get("pdf_link"),
                    "relevance_score": a.get("final_score", a.get("combined_score", 0)),
                    "type": "case",
                })
            else:
                sources.append({
                    "document": a.get("document_title", "Unknown"),
                    "article": a.get("article_number", "N/A"),
                    "title": a.get("title", ""),
                    "page_number": a.get("page_number"),
                    "source_file": a.get("source_file", ""),
                    "pdf_link": f"/api/pdf?file={a.get('source_file', '')}&page={a.get('page_number', 1)}" if a.get("source_file") else None,
                    "relevance_score": a.get("final_score", a.get("combined_score", 0)),
                    "type": "article",
                })

        return {
            "answer": answer,
            "sources": sources,
            "context": context,
            "sub_questions": sub_questions,
            "complexity": complexity,
            "retrieval_strategy": strategy['description']
        }